name: Metrics
on:
  # Her gün 00:00'da güncelle
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rumeysatr
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul
          
          # Plugin: Izometrik Takvim (Mühendislik Havası Verir)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Plugin: Diller (Detaylı Analiz)
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          
          # Plugin: Private Repoları da saysın (Önemli!)
          # NOT: Token yetkilerinde 'repo' seçili olmalıdır.
          committer_token: ${{ secrets.GITHUB_TOKEN }}
